# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-22 23:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_item_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='state_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item_name', models.CharField(max_length=100)),
                ('cart_item_description', models.CharField(max_length=500)),
                ('cart_item_price', models.CharField(blank=True, max_length=100)),
                ('cart_session_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'carts',
                'verbose_name': 'cart',
            },
        ),
    ]
