# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-22 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_state_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_cart',
            name='cart_item_price',
            field=models.IntegerField(blank=True, max_length=100),
        ),
    ]
