# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-25 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcart', '0002_auto_20161025_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_cart',
            name='total_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
